language: generic

cache:
  directories:
    - /home/travis/.cargo/
    - target/
  timeout: 1000

install:
  - ci/install.sh

script:
  - ci/test.sh
  - ci/publish.sh

addons:
  firefox: latest
  chrome: stable
