language: generic

install:
  - scripts/install.sh

script:
  - scripts/test.sh

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master

addons:
  firefox: latest
  chrome: stable

notifications:
  email:
    on_success: never
