language: generic

cache:
  directories:
    - /home/travis/.cargo/
    - target/
  timeout: 1000

install:
  - ci/install.sh

script:
  - ci/test.sh

deploy:
  provider: script
  script: ci/publish.sh
  on:
    tags: true

addons:
  firefox: latest
  chrome: stable
