language: rust

cache: cargo

install:
  - rustup default `cat rust-toolchain`
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview

script:
  - cargo test
  - cargo fmt -- --check
  - cargo clippy
  - cargo package

notifications:
  email:
    - robert@resin.io
    - cyryl@resin.io
  on_success: change
  on_failure: always
